### ISSUE TITLE
Navigating to "About" then back to "Home" causes the wall image to disappear

### ISSUE THREAD

**Issue by qwoprocks** [yarkhinephyo/yolo_bouldering#33]
If you upload an image, then navigate to the About page and navigate back to home, **Diagram 1** will be seen. 

#### Expected behaviour
The image should still be there after page navigations

#### Diagram 1
![image](https://user-images.githubusercontent.com/46164638/115962150-8efd6200-a54c-11eb-9160-90e7734ca231.png)

**Comment by wasiqe** [comment]
Hi
https://github.com/yarkhinephyo/yolo_bouldering/pull/41
Tried to fix the issue here will test and give a final fix. 
Need some time to cope up with aws and serverless, any pointers or helper docs to set up dev environment is appreciated.

Thank you.

**Comment by yarkhinephyo** [comment]
Hi!

Thank you so much for the PR.

Just follow the setup instructions to set up the backend dev environment.
But maybe give me an hour? I will create a dev endpoint for you.

Regards,
Phyo

**Comment by yarkhinephyo** [comment]
@wasiqe Can you email me so that I can send you? Thank you :)

**Comment by yarkhinephyo** [comment]
Closed after migration to vue 3 in new code base
