### ISSUE TITLE
Feature/Hide Navbar when editing routes on mobile

### ISSUE THREAD

**Issue by yarkhinephyo** [yarkhinephyo/yolo_bouldering#56]
#### Problem
When editing the climbing route on mobile, the navbar takes up too much space.

#### Solution
Hide the navbar when the user has scrolled until the button segments.
Only for this page (/home), mainly for mobile.

#### Diagram
![image](https://user-images.githubusercontent.com/19868916/119251827-497b9580-bbdb-11eb-850d-b5056f267fac.png)

**Comment by joenchua** [comment]
!

**Comment by yarkhinephyo** [comment]
Closed because subset of #95
